### ISSUE TITLE
Remove introduction_test.exe file from git repo

### ISSUE THREAD

**Issue by PaulBatchelor** [WillBatchelor/CardinalEscape#1]
Git isn't meant to track binary files. They tend to gum up the works.

You can remove the current exe file here with `git rm introduction_test.exe`.

In the future, I would recommend adding a gitignore file for your project which can automatically reject adding exe files in the future. A quick google turns up [this template gitignore for visual studio](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore). You can [download the raw file here](https://raw.githubusercontent.com/github/gitignore/master/VisualStudio.gitignore), then add it to your repo as `.gitignore` in the top-level directory. You can also [take a look at my gitignore file as it is used in Soundpipe](https://github.com/PaulBatchelor/Soundpipe/blob/master/.gitignore)

Hope that helps!

-P

**Comment by WillBatchelor** [comment]
Completely forgot about that. I added a .gitignore and deleted the exe file. Thank you for the help.

**Comment by PaulBatchelor** [comment]
gitignore file actually neads to be .gitignore, not VisualStudio.gitignore.

Can be fixed on the commandline with `git mv VisualStudio.gitignore .gitignore`.

cheers,

-P
